// This file is auto-generated by python-be/scripts/generate_sfx_catalog.py.
export const SFX_CATALOG = [
  'assets/sfx/cartoon/boing.mp3',
  'assets/sfx/cartoon/cartoon-slip.mp3',
  'assets/sfx/cartoon/throw.mp3',
  'assets/sfx/emotion/applause.mp3',
  'assets/sfx/emotion/disapointed.mp3',
  'assets/sfx/emotion/shock.mp3',
  'assets/sfx/emphasis/ding.mp3',
  'assets/sfx/tech/camera-click.mp3',
  'assets/sfx/tech/notification.mp3',
  'assets/sfx/ui/bubble-pop.mp3',
  'assets/sfx/ui/keyboard-typing.mp3',
  'assets/sfx/ui/mouse-click.mp3',
  'assets/sfx/ui/notification.mp3',
  'assets/sfx/ui/pop.mp3',
  'assets/sfx/ui/swipe.mp3',
  'assets/sfx/whoosh/woosh.mp3',
] as const;
