import { EffectCategory } from "./effectCategories";
import { EffectKey, EffectTaxonomyEntry } from "../../types/EffectTypes";

export const effectTaxonomy: Record<
  EffectCategory,
  readonly EffectTaxonomyEntry[]
> = {
  [EffectCategory.Text]: [
    {
      key: "text.popUp",
      label: "Pop Up Title",
      description: "Bold, Montserrat-styled badge that uses the core red gradient to call out educational hooks.",
      category: EffectCategory.Text,
      intents: ["hook", "insight", "educational"],
      defaultDuration: 1.2,
    },
    {
      key: "text.typeOn",
      label: "Type-On Caption",
      description: "Typewriter reveal for subtitles or punch lines.",
      category: EffectCategory.Text,
      intents: ["subtitle", "quote", "narration"],
      defaultDuration: 2,
    },
    {
      key: "text.swipeHighlight",
      label: "Swipe Highlight",
      description: "Highlight bar slides under the selected words.",
      category: EffectCategory.Text,
      intents: ["emphasis", "data-point"],
      defaultDuration: 1,
    },
    {
      key: "text.keywordSubtitleHighlight",
      label: "Keyword Subtitle Highlight",
      description: "Glowing keyword subtitle with a sweeping underline pop.",
      category: EffectCategory.Text,
      intents: ["subtitle", "keyword", "emphasis"],
      defaultDuration: 1.8,
    },
    {
      key: "text.keywordColorHighlight",
      label: "Keyword Color Highlight",
      description: "Keyword-specific color flash with gradient glow.",
      category: EffectCategory.Text,
      intents: ["subtitle", "keyword", "emphasis"],
      defaultDuration: 1.8,
    },
    {
      key: "text.popUp3D",
      label: "3D Pop-Up Text",
      description: "Sit-up / lay-down 3D text animation for bold hooks.",
      category: EffectCategory.Text,
      intents: ["hook", "cta", "hero"],
      defaultDuration: 1.5,
    },
    {
      key: "text.sideFloat",
      label: "Side Float Text",
      description: "Soft drift labels that float in from screen edges.",
      category: EffectCategory.Text,
      intents: ["supporting-text", "callout"],
      defaultDuration: 1.8,
    },
    {
      key: "text.sideFloatLeft",
      label: "Side Float Left",
      description: "Preset for left-side supporting text.",
      category: EffectCategory.Text,
      intents: ["supporting-text"],
      defaultDuration: 1.8,
    },
    {
      key: "text.sideFloatRight",
      label: "Side Float Right",
      description: "Preset for right-side supporting text.",
      category: EffectCategory.Text,
      intents: ["supporting-text"],
      defaultDuration: 1.8,
    },
    {
      key: "text.sequentialList",
      label: "Sequential List Reveal",
      description: "Stacked list appearing sequentially with zoom + fade.",
      category: EffectCategory.Text,
      intents: ["list", "callout"],
      defaultDuration: 2.5,
    },
    {
      key: "text.stepBreakdown",
      label: "Step Breakdown Transition",
      description: "Highlight topic list entries, then spotlight each step with its own card.",
      category: EffectCategory.Text,
      intents: ["curriculum", "process", "chapter-break"],
      defaultDuration: 3,
    },
    {
      key: "text.centralConcept",
      label: "Central Concept Map",
      description: "Circular concept map with a bold core idea and orbiting sub-topics.",
      category: EffectCategory.Text,
      intents: ["concept-map", "structure"],
      defaultDuration: 2.8,
    },
  ],
  [EffectCategory.Motion]: [
    {
      key: "motion.zoomFocus",
      label: "Zoom Focus",
      description: "Quick zoom into focal element with easing.",
      category: EffectCategory.Motion,
      intents: ["beat-emphasis", "before-after", "hook"],
      defaultDuration: 0.8,
    },
    {
      key: "motion.slidePan",
      label: "Slide Pan",
      description: "Horizontal camera pan for transitions.",
      category: EffectCategory.Motion,
      intents: ["transition", "b-roll"],
      defaultDuration: 1.5,
    },
    {
      key: "motion.fadeIn",
      label: "Hero Fade-In",
      description: "Opacity fade for smooth intros.",
      category: EffectCategory.Motion,
      intents: ["intro", "transition"],
      defaultDuration: 1,
    },
    {
      key: "motion.slideUp",
      label: "Slide Up Reveal",
      description: "Vertical slide + fade reveal.",
      category: EffectCategory.Motion,
      intents: ["reveal", "text-entry"],
      defaultDuration: 1,
    },
    {
      key: "motion.zoomIn",
      label: "Zoom In Pulse",
      description: "Subtle zoom punch for emphasis.",
      category: EffectCategory.Motion,
      intents: ["emphasis", "hero"],
      defaultDuration: 1,
    },
    {
      key: "motion.cameraZoomFocus",
      label: "Camera Zoom Focus",
      description: "Punch-in / punch-out camera style move to highlight speaker.",
      category: EffectCategory.Motion,
      intents: ["emphasis", "hero"],
      defaultDuration: 2,
    },
  ],
  [EffectCategory.Chart]: [
    {
      key: "chart.statCard",
      label: "Stat Card Flip",
      description: "Red-on-black stat slab that flips forward to spotlight a metric.",
      category: EffectCategory.Chart,
      intents: ["metric", "insight", "kpi-highlight"],
      defaultDuration: 1.2,
    },
    {
      key: "chart.timelineReveal",
      label: "Timeline Reveal",
      description: "Horizontal roadmap with glowing nodes that narrate each stage.",
      category: EffectCategory.Chart,
      intents: ["roadmap", "process", "education"],
      defaultDuration: 2.4,
    },
    {
      key: "chart.dataReveal",
      label: "Data Visualization Reveal",
      description: "Line chart grid reveals with axes draw, value callouts, and dual series.",
      category: EffectCategory.Chart,
      intents: ["reporting", "comparison", "trend"],
      defaultDuration: 2.8,
    },
    {
      key: "chart.branchTree",
      label: "Branch Tree Expansion",
      description: "Layered triangle-inspired tree that fans out from a core idea.",
      category: EffectCategory.Chart,
      intents: ["flowchart", "structure", "strategy"],
      defaultDuration: 3,
    },
  ],
  [EffectCategory.Background]: [
    {
      key: "background.gradientPulse",
      label: "Gradient Pulse",
      description: "Animated gradient breathing effect.",
      category: EffectCategory.Background,
      intents: ["ambient", "loop"],
      defaultDuration: 3,
    },
    {
      key: "background.particleField",
      label: "Particle Field",
      description: "Soft particle drift for depth.",
      category: EffectCategory.Background,
      intents: ["ambient", "tech"],
      defaultDuration: 4,
    },
    {
      key: "background.noiseBackdrop",
      label: "Noise Backdrop",
      description: "Noise-driven glow backdrop with animated streaks.",
      category: EffectCategory.Background,
      intents: ["ambient", "tech"],
      defaultDuration: 4,
    },
  ],
  [EffectCategory.Overlay]: [
    {
      key: "overlay.lowerThird",
      label: "Lower Third",
      description: "Structured lower third that introduces a presenter with the primary red badge.",
      category: EffectCategory.Overlay,
      intents: ["speaker-id", "brand", "authority"],
      defaultDuration: 1.5,
    },
    {
      key: "overlay.badgePulse",
      label: "Badge Pulse",
      description: "Glowing circular badge designed for metrics and CTA emphasis.",
      category: EffectCategory.Overlay,
      intents: ["cta", "metric", "highlight"],
      defaultDuration: 0.9,
    },
    {
      key: "overlay.sectionTitle",
      label: "Section Title Overlay",
      description: "Glass-style headline card that frames key transitions with bold typography.",
      category: EffectCategory.Overlay,
      intents: ["section-break", "headline"],
      defaultDuration: 2,
    },
    {
      key: "overlay.iconHighlight",
      label: "Icon Highlight",
      description: "Floating badge that spotlights a symbol with gradient glow before fading.",
      category: EffectCategory.Overlay,
      intents: ["concept-highlight", "badge"],
      defaultDuration: 1.8,
    },
    {
      key: "overlay.socialIconPop",
      label: "Social Icon Pop",
      description: "Social platform badges emerge with red outlines and educational callouts.",
      category: EffectCategory.Overlay,
      intents: ["platform-callout", "social-proof"],
      defaultDuration: 1.5,
    },
    {
      key: "overlay.appIntro",
      label: "App Intro Lower Third",
      description: "Gradient lower-third with icon, name, tagline, and link for platform spotlight.",
      category: EffectCategory.Overlay,
      intents: ["brand-callout", "intro", "platform"],
      defaultDuration: 2.5,
    },
    {
      key: "overlay.audioVisualizer",
      label: "Audio Visualizer",
      description: "Voice interaction waveform overlay with glowing spectrum and transcript label.",
      category: EffectCategory.Overlay,
      intents: ["audio", "voice", "ai-interface"],
      defaultDuration: 2.5,
    },
  ],
};

export const allEffectKeys: EffectKey[] = Object.values(effectTaxonomy).flatMap(
  (entries) => entries.map((entry) => entry.key as EffectKey)
);

export const isEffectKey = (value: string): value is EffectKey =>
  allEffectKeys.includes(value as EffectKey);
